name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Skip PyPI Publishing
        if: ${{ secrets.PYPI_API_TOKEN == '' }}
        run: |
          echo "⚠️  PyPI publishing skipped - PYPI_API_TOKEN not configured"
          echo "To enable PyPI publishing:"
          echo "1. Create a PyPI account at https://pypi.org"
          echo "2. Generate an API token at https://pypi.org/manage/account/token/"
          echo "3. Add the token as PYPI_API_TOKEN secret in GitHub repository settings"

      - name: Publish to PyPI
        if: ${{ secrets.PYPI_API_TOKEN != '' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true 